# Generated by Django 4.2.5 on 2023-09-16 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid
import v1.models.mixins.slug_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(default=v1.models.mixins.SlugMixin._slug_generator, max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(default=v1.models.mixins.SlugMixin._slug_generator, max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.directory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
