# Generated by Django 4.2.5 on 2023-09-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='uuid',
            new_name='id',
        ),
    ]
