# Generated by Django 4.2.5 on 2023-09-16 11:51

from django.db import migrations, models
import django.utils.timezone
import v1.models.mixins.slug_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_rename_uuid_deck_id_rename_uuid_directory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.CharField(default=v1.models.mixins.slug_mixin._slug_generator, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='slug',
            field=models.CharField(default=v1.models.mixins.slug_mixin._slug_generator, max_length=16, unique=True),
        ),
    ]
