# Generated by Django 4.2.5 on 2023-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_deck_created_at_deck_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='colour',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
