# Generated by Django 4.2.5 on 2023-09-17 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_directory_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('front', models.TextField(default='')),
                ('back', models.JSONField(default={})),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
