# Generated by Django 4.2.5 on 2023-09-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.JSONField(default=dict),
        ),
    ]
