# Generated by Django 4.2.5 on 2023-09-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_alter_card_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(default=''),
        ),
    ]
