# Generated by Django 4.2.5 on 2023-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_card_data_alter_card_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
