# Generated by Django 4.2.5 on 2023-09-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_alter_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
