# Generated by Django 4.2.5 on 2023-09-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_deck_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='directory',
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
