# Generated by Django 4.2.5 on 2023-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_card_user_alter_deck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='example',
            field=models.TextField(default=''),
        ),
    ]
