# Generated by Django 4.2.5 on 2023-11-09 11:49

from django.db import migrations, models
import v1.models.mixins.slug_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_card_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.CharField(db_index=True, default=v1.models.mixins.slug_mixin._slug_generator, max_length=16, unique=True),
        ),
    ]
