# Generated by Django 4.2.5 on 2023-11-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_alter_deck_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='back_language',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='front_language',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
