# Generated by Django 4.2.5 on 2023-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_deck_back_language_deck_front_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='back_language',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='front_language',
        ),
        migrations.AddField(
            model_name='deck',
            name='back_language_iso',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='front_language_iso',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
