# Generated by Django 4.2.5 on 2023-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_remove_deck_back_language_remove_deck_front_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='back_language_iso',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='front_language_iso',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
