# Generated by Django 4.2.5 on 2023-11-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_alter_deck_back_language_iso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='back_language_iso',
            new_name='back_language_code',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='front_language_iso',
            new_name='front_language_code',
        ),
    ]
