# Generated by Django 4.2.5 on 2023-11-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_rename_back_language_iso_deck_back_language_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='example',
            new_name='example_front',
        ),
        migrations.AddField(
            model_name='card',
            name='example_back',
            field=models.TextField(default=''),
        ),
    ]
