# Generated by Django 4.2.5 on 2023-11-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0020_rename_example_card_example_front_card_example_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='data',
        ),
    ]
