# Generated by Django 4.2.5 on 2023-12-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0025_alter_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
