# Generated by Django 4.2.5 on 2024-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0027_tag_tag_unique_tag_in_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cards',
            field=models.ManyToManyField(related_name='tags', to='v1.card'),
        ),
    ]
