# Generated by Django 4.2.5 on 2024-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_tag_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.CharField(db_index=True, max_length=16, null=True, unique=True),
        ),
    ]
